/******************************************************************* 
 * Header file generated by Protoc for Embedded C.                 *
 * Version 1.0M4 (2013-03-31)                                      *
 *                                                                 *
 * Copyright (c) 2009-2013                                         *
 * Technische Universitaet Muenchen                                *
 * http://www4.in.tum.de/                                          *
 *                                                                 *
 * Source : Testmessage.proto
 *                                                                 *
 * Do not edit.                                                    *
 *******************************************************************/

#ifndef _Testmessage_H
#define _Testmessage_H

#ifdef __cplusplus
  extern "C" {
#endif

#include <stdint.h>

/*******************************************************************
 * General functions
 *******************************************************************/

/*
 * returns the size of a length delimited message which also 
 * contains the first bytes for the length encoding.
 */
unsigned long Message_get_delimited_size(void *_buffer, int offset);

/*
 * Tests whether a message can be completely read from the given buffer at
 * the offset. The bytes [offset..offset+length-1] are interpreted.
 *
 * Returns 1 (true) if buffer[offset..offset+length-1] contains a complete
 * message or 0 (false) otherwise.
 */
int Message_can_read_delimited_from(void *_buffer, int offset, unsigned int length);



/*******************************************************************
 * Message: Testmessage.proto, line 3
 *******************************************************************/

/* Maximum size of a serialized testmessage-message, useful for buffer allocation. */
#define MAX_testmessage_SIZE 26

/* Structure that holds a deserialized testmessage-message. */
typedef struct testmessage {
    int32_t _i32thefirst;
    int32_t _i32thesecond;
}testmessage;

/*
 * Serialize a Person-message into the given buffer at offset and return
 * new offset for optional next message.
 */
int testmessage_write_delimited_to(struct testmessage *_testmessage, void *_buffer, int offset);

int testmessage_write(struct testmessage *_testmessage, void *_buffer, int offset);

/*
 * Serialize a Person-message together with its tag into the given buffer 
 * at offset and return new offset for optional next message.
 * Is useful if a Person-message is embedded in another message.
 */
int testmessage_write_with_tag(struct testmessage *_testmessage, void *_buffer, int offset, int tag);

/*
 * Deserialize a Person-message from the given buffer at offset and return
 * new offset for optional next message.
 *
 * Note: All fields in _Person will be reset to 0 before _buffer is interpreted.
 */
int testmessage_read_delimited_from(void *_buffer, struct testmessage *_testmessage, int offset);

int testmessage_read(void *_buffer, struct testmessage *_testmessage, int offset, int limit);



#ifdef __cplusplus
  }
#endif

#endif

