/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>

#ifndef _dof_feedback_t_h
#define _dof_feedback_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "int32.h"
#include "int32.h"
#include "int32.h"
#include "int32.h"
#include "int32.h"
typedef struct _dof_feedback_t dof_feedback_t;
struct _dof_feedback_t
{
    int32      status;
    int32      timestamp;
    int32      dof;
    float      kp;
    float      ki;
    float      kd;
    float      dot_kp;
    float      dot_ki;
    float      dot_kd;
    float      setpt;
    float      dot_setpt;
    int32      setpt_tstamp;
    int32      dot_setpt_tstamp;
    float      filter_state;
    float      dot_filter_state;
    float      raw_state;
    float      dot_raw_state;
};

dof_feedback_t   *dof_feedback_t_copy(const dof_feedback_t *p);
void dof_feedback_t_destroy(dof_feedback_t *p);

int  dof_feedback_t_encode(void *buf, int offset, int maxlen, const dof_feedback_t *p);
int  dof_feedback_t_decode(const void *buf, int offset, int maxlen, dof_feedback_t *p);
int  dof_feedback_t_decode_cleanup(dof_feedback_t *p);
int  dof_feedback_t_encoded_size(const dof_feedback_t *p);

// LCM support functions. Users should not call these
int64_t __dof_feedback_t_get_hash(void);
int64_t __dof_feedback_t_hash_recursive(const __lcm_hash_ptr *p);
int     __dof_feedback_t_encode_array(void *buf, int offset, int maxlen, const dof_feedback_t *p, int elements);
int     __dof_feedback_t_decode_array(const void *buf, int offset, int maxlen, dof_feedback_t *p, int elements);
int     __dof_feedback_t_decode_array_cleanup(dof_feedback_t *p, int elements);
int     __dof_feedback_t_encoded_array_size(const dof_feedback_t *p, int elements);
int     __dof_feedback_t_clone_array(const dof_feedback_t *p, dof_feedback_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
