tuning: main.cpp serial.cpp serial.h seriallcm.cpp seriallcm.h lcmlite.c lcmlite.h target_t.h target_t.c feedback_t.c feedback_t.h position_t.c position_t.h tuning_t.c tuning_t.h data_link.c data_link.h
	g++ -std=c++11 main.cpp serial.cpp seriallcm.cpp lcmlite.c target_t.c feedback_t.c position_t.c tuning_t.c dof_feedback_t.c djiout_feedback_t.c data_link.c str_log_t.c -o tuning

