/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>

#ifndef _str_log_t_h
#define _str_log_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "int32.h"
typedef struct _str_log_t str_log_t;
struct _str_log_t
{
    int32      timestamp;
    char*      mess;
};

str_log_t   *str_log_t_copy(const str_log_t *p);
void str_log_t_destroy(str_log_t *p);

int  str_log_t_encode(void *buf, int offset, int maxlen, const str_log_t *p);
int  str_log_t_decode(const void *buf, int offset, int maxlen, str_log_t *p);
int  str_log_t_decode_cleanup(str_log_t *p);
int  str_log_t_encoded_size(const str_log_t *p);

// LCM support functions. Users should not call these
int64_t __str_log_t_get_hash(void);
int64_t __str_log_t_hash_recursive(const __lcm_hash_ptr *p);
int     __str_log_t_encode_array(void *buf, int offset, int maxlen, const str_log_t *p, int elements);
int     __str_log_t_decode_array(const void *buf, int offset, int maxlen, str_log_t *p, int elements);
int     __str_log_t_decode_array_cleanup(str_log_t *p, int elements);
int     __str_log_t_encoded_array_size(const str_log_t *p, int elements);
int     __str_log_t_clone_array(const str_log_t *p, str_log_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
