/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "str_log_t.h"

static int __str_log_t_hash_computed;
static int64_t __str_log_t_hash;

int64_t __str_log_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __str_log_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__str_log_t_get_hash };
    (void) cp;

    int64_t hash = 0xf9c0e64c6b16c92dLL
         + __int32_hash_recursive(&cp)
         + __string_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __str_log_t_get_hash(void)
{
    if (!__str_log_t_hash_computed) {
        __str_log_t_hash = __str_log_t_hash_recursive(NULL);
        __str_log_t_hash_computed = 1;
    }

    return __str_log_t_hash;
}

int __str_log_t_encode_array(void *buf, int offset, int maxlen, const str_log_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_encode_array(buf, offset + pos, maxlen - pos, &(p[element].mess), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int str_log_t_encode(void *buf, int offset, int maxlen, const str_log_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __str_log_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __str_log_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __str_log_t_encoded_array_size(const str_log_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __string_encoded_array_size(&(p[element].mess), 1);

    }
    return size;
}

int str_log_t_encoded_size(const str_log_t *p)
{
    return 8 + __str_log_t_encoded_array_size(p, 1);
}

int __str_log_t_decode_array(const void *buf, int offset, int maxlen, str_log_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __string_decode_array(buf, offset + pos, maxlen - pos, &(p[element].mess), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __str_log_t_decode_array_cleanup(str_log_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __string_decode_array_cleanup(&(p[element].mess), 1);

    }
    return 0;
}

int str_log_t_decode(const void *buf, int offset, int maxlen, str_log_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __str_log_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __str_log_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int str_log_t_decode_cleanup(str_log_t *p)
{
    return __str_log_t_decode_array_cleanup(p, 1);
}

int __str_log_t_clone_array(const str_log_t *p, str_log_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __string_clone_array(&(p[element].mess), &(q[element].mess), 1);

    }
    return 0;
}

str_log_t *str_log_t_copy(const str_log_t *p)
{
    str_log_t *q = (str_log_t*) malloc(sizeof(str_log_t));
    __str_log_t_clone_array(p, q, 1);
    return q;
}

void str_log_t_destroy(str_log_t *p)
{
    __str_log_t_decode_array_cleanup(p, 1);
    free(p);
}

