/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "djiout_feedback_t.h"

static int __djiout_feedback_t_hash_computed;
static int64_t __djiout_feedback_t_hash;

int64_t __djiout_feedback_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __djiout_feedback_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__djiout_feedback_t_get_hash };
    (void) cp;

    int64_t hash = 0x5ab78047f8fe3064LL
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __djiout_feedback_t_get_hash(void)
{
    if (!__djiout_feedback_t_hash_computed) {
        __djiout_feedback_t_hash = __djiout_feedback_t_hash_recursive(NULL);
        __djiout_feedback_t_hash_computed = 1;
    }

    return __djiout_feedback_t_hash;
}

int __djiout_feedback_t_encode_array(void *buf, int offset, int maxlen, const djiout_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yawdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].fz), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int djiout_feedback_t_encode(void *buf, int offset, int maxlen, const djiout_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __djiout_feedback_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __djiout_feedback_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __djiout_feedback_t_encoded_array_size(const djiout_feedback_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].roll), 1);

        size += __float_encoded_array_size(&(p[element].pitch), 1);

        size += __float_encoded_array_size(&(p[element].yawdot), 1);

        size += __float_encoded_array_size(&(p[element].fz), 1);

    }
    return size;
}

int djiout_feedback_t_encoded_size(const djiout_feedback_t *p)
{
    return 8 + __djiout_feedback_t_encoded_array_size(p, 1);
}

int __djiout_feedback_t_decode_array(const void *buf, int offset, int maxlen, djiout_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].roll), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pitch), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yawdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].fz), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __djiout_feedback_t_decode_array_cleanup(djiout_feedback_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].roll), 1);

        __float_decode_array_cleanup(&(p[element].pitch), 1);

        __float_decode_array_cleanup(&(p[element].yawdot), 1);

        __float_decode_array_cleanup(&(p[element].fz), 1);

    }
    return 0;
}

int djiout_feedback_t_decode(const void *buf, int offset, int maxlen, djiout_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __djiout_feedback_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __djiout_feedback_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int djiout_feedback_t_decode_cleanup(djiout_feedback_t *p)
{
    return __djiout_feedback_t_decode_array_cleanup(p, 1);
}

int __djiout_feedback_t_clone_array(const djiout_feedback_t *p, djiout_feedback_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].roll), &(q[element].roll), 1);

        __float_clone_array(&(p[element].pitch), &(q[element].pitch), 1);

        __float_clone_array(&(p[element].yawdot), &(q[element].yawdot), 1);

        __float_clone_array(&(p[element].fz), &(q[element].fz), 1);

    }
    return 0;
}

djiout_feedback_t *djiout_feedback_t_copy(const djiout_feedback_t *p)
{
    djiout_feedback_t *q = (djiout_feedback_t*) malloc(sizeof(djiout_feedback_t));
    __djiout_feedback_t_clone_array(p, q, 1);
    return q;
}

void djiout_feedback_t_destroy(djiout_feedback_t *p)
{
    __djiout_feedback_t_decode_array_cleanup(p, 1);
    free(p);
}

