/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "dof_feedback_t.h"

static int __dof_feedback_t_hash_computed;
static int64_t __dof_feedback_t_hash;

int64_t __dof_feedback_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __dof_feedback_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__dof_feedback_t_get_hash };
    (void) cp;

    int64_t hash = 0xd9c2535396f178dbLL
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __dof_feedback_t_get_hash(void)
{
    if (!__dof_feedback_t_hash_computed) {
        __dof_feedback_t_hash = __dof_feedback_t_hash_recursive(NULL);
        __dof_feedback_t_hash_computed = 1;
    }

    return __dof_feedback_t_hash;
}

int __dof_feedback_t_encode_array(void *buf, int offset, int maxlen, const dof_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dof), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ki), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_ki), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].setpt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_setpt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].setpt_tstamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_setpt_tstamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].filter_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_filter_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].raw_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_raw_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int dof_feedback_t_encode(void *buf, int offset, int maxlen, const dof_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __dof_feedback_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __dof_feedback_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __dof_feedback_t_encoded_array_size(const dof_feedback_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].status), 1);

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __int32_encoded_array_size(&(p[element].dof), 1);

        size += __float_encoded_array_size(&(p[element].kp), 1);

        size += __float_encoded_array_size(&(p[element].ki), 1);

        size += __float_encoded_array_size(&(p[element].kd), 1);

        size += __float_encoded_array_size(&(p[element].dot_kp), 1);

        size += __float_encoded_array_size(&(p[element].dot_ki), 1);

        size += __float_encoded_array_size(&(p[element].dot_kd), 1);

        size += __float_encoded_array_size(&(p[element].setpt), 1);

        size += __float_encoded_array_size(&(p[element].dot_setpt), 1);

        size += __int32_encoded_array_size(&(p[element].setpt_tstamp), 1);

        size += __int32_encoded_array_size(&(p[element].dot_setpt_tstamp), 1);

        size += __float_encoded_array_size(&(p[element].filter_state), 1);

        size += __float_encoded_array_size(&(p[element].dot_filter_state), 1);

        size += __float_encoded_array_size(&(p[element].raw_state), 1);

        size += __float_encoded_array_size(&(p[element].dot_raw_state), 1);

    }
    return size;
}

int dof_feedback_t_encoded_size(const dof_feedback_t *p)
{
    return 8 + __dof_feedback_t_encoded_array_size(p, 1);
}

int __dof_feedback_t_decode_array(const void *buf, int offset, int maxlen, dof_feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dof), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ki), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_kp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_ki), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_kd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].setpt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_setpt), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].setpt_tstamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_setpt_tstamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].filter_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_filter_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].raw_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].dot_raw_state), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __dof_feedback_t_decode_array_cleanup(dof_feedback_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].status), 1);

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __int32_decode_array_cleanup(&(p[element].dof), 1);

        __float_decode_array_cleanup(&(p[element].kp), 1);

        __float_decode_array_cleanup(&(p[element].ki), 1);

        __float_decode_array_cleanup(&(p[element].kd), 1);

        __float_decode_array_cleanup(&(p[element].dot_kp), 1);

        __float_decode_array_cleanup(&(p[element].dot_ki), 1);

        __float_decode_array_cleanup(&(p[element].dot_kd), 1);

        __float_decode_array_cleanup(&(p[element].setpt), 1);

        __float_decode_array_cleanup(&(p[element].dot_setpt), 1);

        __int32_decode_array_cleanup(&(p[element].setpt_tstamp), 1);

        __int32_decode_array_cleanup(&(p[element].dot_setpt_tstamp), 1);

        __float_decode_array_cleanup(&(p[element].filter_state), 1);

        __float_decode_array_cleanup(&(p[element].dot_filter_state), 1);

        __float_decode_array_cleanup(&(p[element].raw_state), 1);

        __float_decode_array_cleanup(&(p[element].dot_raw_state), 1);

    }
    return 0;
}

int dof_feedback_t_decode(const void *buf, int offset, int maxlen, dof_feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __dof_feedback_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __dof_feedback_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int dof_feedback_t_decode_cleanup(dof_feedback_t *p)
{
    return __dof_feedback_t_decode_array_cleanup(p, 1);
}

int __dof_feedback_t_clone_array(const dof_feedback_t *p, dof_feedback_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].status), &(q[element].status), 1);

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __int32_clone_array(&(p[element].dof), &(q[element].dof), 1);

        __float_clone_array(&(p[element].kp), &(q[element].kp), 1);

        __float_clone_array(&(p[element].ki), &(q[element].ki), 1);

        __float_clone_array(&(p[element].kd), &(q[element].kd), 1);

        __float_clone_array(&(p[element].dot_kp), &(q[element].dot_kp), 1);

        __float_clone_array(&(p[element].dot_ki), &(q[element].dot_ki), 1);

        __float_clone_array(&(p[element].dot_kd), &(q[element].dot_kd), 1);

        __float_clone_array(&(p[element].setpt), &(q[element].setpt), 1);

        __float_clone_array(&(p[element].dot_setpt), &(q[element].dot_setpt), 1);

        __int32_clone_array(&(p[element].setpt_tstamp), &(q[element].setpt_tstamp), 1);

        __int32_clone_array(&(p[element].dot_setpt_tstamp), &(q[element].dot_setpt_tstamp), 1);

        __float_clone_array(&(p[element].filter_state), &(q[element].filter_state), 1);

        __float_clone_array(&(p[element].dot_filter_state), &(q[element].dot_filter_state), 1);

        __float_clone_array(&(p[element].raw_state), &(q[element].raw_state), 1);

        __float_clone_array(&(p[element].dot_raw_state), &(q[element].dot_raw_state), 1);

    }
    return 0;
}

dof_feedback_t *dof_feedback_t_copy(const dof_feedback_t *p)
{
    dof_feedback_t *q = (dof_feedback_t*) malloc(sizeof(dof_feedback_t));
    __dof_feedback_t_clone_array(p, q, 1);
    return q;
}

void dof_feedback_t_destroy(dof_feedback_t *p)
{
    __dof_feedback_t_decode_array_cleanup(p, 1);
    free(p);
}

