/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "feedback_t.h"

static int __feedback_t_hash_computed;
static int64_t __feedback_t_hash;

int64_t __feedback_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __feedback_t_get_hash)
            return 0;

    const __lcm_hash_ptr cp = { p, (void*)__feedback_t_get_hash };
    (void) cp;

    int64_t hash = 0xfa1776c16a7f5b10LL
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __feedback_t_get_hash(void)
{
    if (!__feedback_t_hash_computed) {
        __feedback_t_hash = __feedback_t_hash_recursive(NULL);
        __feedback_t_hash_computed = 1;
    }

    return __feedback_t_hash;
}

int __feedback_t_encode_array(void *buf, int offset, int maxlen, const feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].xest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].yest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].zest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].hest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ydot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].Ax), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].Ay), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].Az), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].rdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].pdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].hdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int feedback_t_encode(void *buf, int offset, int maxlen, const feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __feedback_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __feedback_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __feedback_t_encoded_array_size(const feedback_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].cmd), 1);

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].xest), 1);

        size += __float_encoded_array_size(&(p[element].yest), 1);

        size += __float_encoded_array_size(&(p[element].zest), 1);

        size += __float_encoded_array_size(&(p[element].rest), 1);

        size += __float_encoded_array_size(&(p[element].pest), 1);

        size += __float_encoded_array_size(&(p[element].hest), 1);

        size += __int32_encoded_array_size(&(p[element].status), 1);

        size += __float_encoded_array_size(&(p[element].xdot), 1);

        size += __float_encoded_array_size(&(p[element].ydot), 1);

        size += __float_encoded_array_size(&(p[element].zdot), 1);

        size += __float_encoded_array_size(&(p[element].Ax), 1);

        size += __float_encoded_array_size(&(p[element].Ay), 1);

        size += __float_encoded_array_size(&(p[element].Az), 1);

        size += __float_encoded_array_size(&(p[element].rdot), 1);

        size += __float_encoded_array_size(&(p[element].pdot), 1);

        size += __float_encoded_array_size(&(p[element].hdot), 1);

    }
    return size;
}

int feedback_t_encoded_size(const feedback_t *p)
{
    return 8 + __feedback_t_encoded_array_size(p, 1);
}

int __feedback_t_decode_array(const void *buf, int offset, int maxlen, feedback_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].xest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].yest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].zest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].hest), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].status), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ydot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].Ax), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].Ay), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].Az), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].rdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].pdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].hdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __feedback_t_decode_array_cleanup(feedback_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].cmd), 1);

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].xest), 1);

        __float_decode_array_cleanup(&(p[element].yest), 1);

        __float_decode_array_cleanup(&(p[element].zest), 1);

        __float_decode_array_cleanup(&(p[element].rest), 1);

        __float_decode_array_cleanup(&(p[element].pest), 1);

        __float_decode_array_cleanup(&(p[element].hest), 1);

        __int32_decode_array_cleanup(&(p[element].status), 1);

        __float_decode_array_cleanup(&(p[element].xdot), 1);

        __float_decode_array_cleanup(&(p[element].ydot), 1);

        __float_decode_array_cleanup(&(p[element].zdot), 1);

        __float_decode_array_cleanup(&(p[element].Ax), 1);

        __float_decode_array_cleanup(&(p[element].Ay), 1);

        __float_decode_array_cleanup(&(p[element].Az), 1);

        __float_decode_array_cleanup(&(p[element].rdot), 1);

        __float_decode_array_cleanup(&(p[element].pdot), 1);

        __float_decode_array_cleanup(&(p[element].hdot), 1);

    }
    return 0;
}

int feedback_t_decode(const void *buf, int offset, int maxlen, feedback_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __feedback_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __feedback_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int feedback_t_decode_cleanup(feedback_t *p)
{
    return __feedback_t_decode_array_cleanup(p, 1);
}

int __feedback_t_clone_array(const feedback_t *p, feedback_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].cmd), &(q[element].cmd), 1);

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].xest), &(q[element].xest), 1);

        __float_clone_array(&(p[element].yest), &(q[element].yest), 1);

        __float_clone_array(&(p[element].zest), &(q[element].zest), 1);

        __float_clone_array(&(p[element].rest), &(q[element].rest), 1);

        __float_clone_array(&(p[element].pest), &(q[element].pest), 1);

        __float_clone_array(&(p[element].hest), &(q[element].hest), 1);

        __int32_clone_array(&(p[element].status), &(q[element].status), 1);

        __float_clone_array(&(p[element].xdot), &(q[element].xdot), 1);

        __float_clone_array(&(p[element].ydot), &(q[element].ydot), 1);

        __float_clone_array(&(p[element].zdot), &(q[element].zdot), 1);

        __float_clone_array(&(p[element].Ax), &(q[element].Ax), 1);

        __float_clone_array(&(p[element].Ay), &(q[element].Ay), 1);

        __float_clone_array(&(p[element].Az), &(q[element].Az), 1);

        __float_clone_array(&(p[element].rdot), &(q[element].rdot), 1);

        __float_clone_array(&(p[element].pdot), &(q[element].pdot), 1);

        __float_clone_array(&(p[element].hdot), &(q[element].hdot), 1);

    }
    return 0;
}

feedback_t *feedback_t_copy(const feedback_t *p)
{
    feedback_t *q = (feedback_t*) malloc(sizeof(feedback_t));
    __feedback_t_clone_array(p, q, 1);
    return q;
}

void feedback_t_destroy(feedback_t *p)
{
    __feedback_t_decode_array_cleanup(p, 1);
    free(p);
}

