/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include <lcm/lcm_coretypes.h>

#ifndef _position_t_h
#define _position_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "int32.h"
#include "int32.h"
typedef struct _position_t position_t;
struct _position_t
{
    int32      cmd;
    int32      timestamp;
    float      x;
    float      y;
    float      z;
    float      h;
};

position_t   *position_t_copy(const position_t *p);
void position_t_destroy(position_t *p);

int  position_t_encode(void *buf, int offset, int maxlen, const position_t *p);
int  position_t_decode(const void *buf, int offset, int maxlen, position_t *p);
int  position_t_decode_cleanup(position_t *p);
int  position_t_encoded_size(const position_t *p);

// LCM support functions. Users should not call these
int64_t __position_t_get_hash(void);
int64_t __position_t_hash_recursive(const __lcm_hash_ptr *p);
int     __position_t_encode_array(void *buf, int offset, int maxlen, const position_t *p, int elements);
int     __position_t_decode_array(const void *buf, int offset, int maxlen, position_t *p, int elements);
int     __position_t_decode_array_cleanup(position_t *p, int elements);
int     __position_t_encoded_array_size(const position_t *p, int elements);
int     __position_t_clone_array(const position_t *p, position_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
