/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _feedback_t_h
#define _feedback_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "int32.h"
#include "int32.h"
#include "int32.h"
typedef struct _feedback_t feedback_t;
struct _feedback_t
{
    int32      cmd;
    int32      timestamp;
    float      xest;
    float      yest;
    float      zest;
    float      rest;
    float      pest;
    float      hest;
    int32      status;
    float      xdot;
    float      ydot;
    float      zdot;
    float      Ax;
    float      Ay;
    float      Az;
    float      rdot;
    float      pdot;
    float      hdot;
};

feedback_t   *feedback_t_copy(const feedback_t *p);
void feedback_t_destroy(feedback_t *p);

int  feedback_t_encode(void *buf, int offset, int maxlen, const feedback_t *p);
int  feedback_t_decode(const void *buf, int offset, int maxlen, feedback_t *p);
int  feedback_t_decode_cleanup(feedback_t *p);
int  feedback_t_encoded_size(const feedback_t *p);

// LCM support functions. Users should not call these
int64_t __feedback_t_get_hash(void);
int64_t __feedback_t_hash_recursive(const __lcm_hash_ptr *p);
int     __feedback_t_encode_array(void *buf, int offset, int maxlen, const feedback_t *p, int elements);
int     __feedback_t_decode_array(const void *buf, int offset, int maxlen, feedback_t *p, int elements);
int     __feedback_t_decode_array_cleanup(feedback_t *p, int elements);
int     __feedback_t_encoded_array_size(const feedback_t *p, int elements);
int     __feedback_t_clone_array(const feedback_t *p, feedback_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
