/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _tuning_t_h
#define _tuning_t_h

#ifdef __cplusplus
extern "C" {
#endif

#include "int32.h"
#include "int32.h"
typedef struct _tuning_t tuning_t;
struct _tuning_t
{
    int32      cmd;
    int32      timestamp;
    float      KPX;
    float      KIX;
    float      KDX;
    float      KPY;
    float      KIY;
    float      KDY;
    float      KPZ;
    float      KIZ;
    float      KDZ;
    float      KPXdot;
    float      KIXdot;
    float      KDXdot;
    float      KPYdot;
    float      KIYdot;
    float      KDYdot;
    float      KPZdot;
    float      KIZdot;
    float      KDZdot;
    float      KPH;
    float      KIH;
    float      KDH;
    float      x;
    float      y;
    float      z;
    float      h;
    float      xdot;
    float      ydot;
    float      zdot;
};

tuning_t   *tuning_t_copy(const tuning_t *p);
void tuning_t_destroy(tuning_t *p);

int  tuning_t_encode(void *buf, int offset, int maxlen, const tuning_t *p);
int  tuning_t_decode(const void *buf, int offset, int maxlen, tuning_t *p);
int  tuning_t_decode_cleanup(tuning_t *p);
int  tuning_t_encoded_size(const tuning_t *p);

// LCM support functions. Users should not call these
int64_t __tuning_t_get_hash(void);
int64_t __tuning_t_hash_recursive(const __lcm_hash_ptr *p);
int     __tuning_t_encode_array(void *buf, int offset, int maxlen, const tuning_t *p, int elements);
int     __tuning_t_decode_array(const void *buf, int offset, int maxlen, tuning_t *p, int elements);
int     __tuning_t_decode_array_cleanup(tuning_t *p, int elements);
int     __tuning_t_encoded_array_size(const tuning_t *p, int elements);
int     __tuning_t_clone_array(const tuning_t *p, tuning_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
