/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _emergency_t_h
#define _emergency_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define EMERGENCY_T_NORMAL 0
#define EMERGENCY_T_LOW_BATTERY 1
#define EMERGENCY_T_KILL 2

typedef struct _emergency_t emergency_t;
struct _emergency_t
{
    int8_t     status;
};

emergency_t   *emergency_t_copy(const emergency_t *p);
void emergency_t_destroy(emergency_t *p);

int  emergency_t_encode(void *buf, int offset, int maxlen, const emergency_t *p);
int  emergency_t_decode(const void *buf, int offset, int maxlen, emergency_t *p);
int  emergency_t_decode_cleanup(emergency_t *p);
int  emergency_t_encoded_size(const emergency_t *p);

// LCM support functions. Users should not call these
int64_t __emergency_t_get_hash(void);
int64_t __emergency_t_hash_recursive(const __lcm_hash_ptr *p);
int     __emergency_t_encode_array(void *buf, int offset, int maxlen, const emergency_t *p, int elements);
int     __emergency_t_decode_array(const void *buf, int offset, int maxlen, emergency_t *p, int elements);
int     __emergency_t_decode_array_cleanup(emergency_t *p, int elements);
int     __emergency_t_encoded_array_size(const emergency_t *p, int elements);
int     __emergency_t_clone_array(const emergency_t *p, emergency_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
