/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _raw_pose_t_h
#define _raw_pose_t_h

#ifdef __cplusplus
extern "C" {
#endif

typedef struct _raw_pose_t raw_pose_t;
struct _raw_pose_t
{
    float      x;
    float      y;
    float      yaw;
    int64_t    utime;
};

raw_pose_t   *raw_pose_t_copy(const raw_pose_t *p);
void raw_pose_t_destroy(raw_pose_t *p);

int  raw_pose_t_encode(void *buf, int offset, int maxlen, const raw_pose_t *p);
int  raw_pose_t_decode(const void *buf, int offset, int maxlen, raw_pose_t *p);
int  raw_pose_t_decode_cleanup(raw_pose_t *p);
int  raw_pose_t_encoded_size(const raw_pose_t *p);

// LCM support functions. Users should not call these
int64_t __raw_pose_t_get_hash(void);
int64_t __raw_pose_t_hash_recursive(const __lcm_hash_ptr *p);
int     __raw_pose_t_encode_array(void *buf, int offset, int maxlen, const raw_pose_t *p, int elements);
int     __raw_pose_t_decode_array(const void *buf, int offset, int maxlen, raw_pose_t *p, int elements);
int     __raw_pose_t_decode_array_cleanup(raw_pose_t *p, int elements);
int     __raw_pose_t_encoded_array_size(const raw_pose_t *p, int elements);
int     __raw_pose_t_clone_array(const raw_pose_t *p, raw_pose_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
