/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _setpt_t_h
#define _setpt_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define SETPT_T_POSE_SETPT 0
#define SETPT_T_RATE_SETPT 1
#define SETPT_T_NORMAL 0
#define SETPT_T_TAKEOFF 1
#define SETPT_T_LAND 2
#define SETPT_T_IDLE 3

typedef struct _setpt_t setpt_t;
struct _setpt_t
{
    float      x;
    float      y;
    float      z;
    float      yaw;
    int8_t     flags;
    int8_t     setptType;
    int32_t    utime;
};

setpt_t   *setpt_t_copy(const setpt_t *p);
void setpt_t_destroy(setpt_t *p);

int  setpt_t_encode(void *buf, int offset, int maxlen, const setpt_t *p);
int  setpt_t_decode(const void *buf, int offset, int maxlen, setpt_t *p);
int  setpt_t_decode_cleanup(setpt_t *p);
int  setpt_t_encoded_size(const setpt_t *p);

// LCM support functions. Users should not call these
int64_t __setpt_t_get_hash(void);
int64_t __setpt_t_hash_recursive(const __lcm_hash_ptr *p);
int     __setpt_t_encode_array(void *buf, int offset, int maxlen, const setpt_t *p, int elements);
int     __setpt_t_decode_array(const void *buf, int offset, int maxlen, setpt_t *p, int elements);
int     __setpt_t_decode_array_cleanup(setpt_t *p, int elements);
int     __setpt_t_encoded_array_size(const setpt_t *p, int elements);
int     __setpt_t_clone_array(const setpt_t *p, setpt_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
