/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <stdint.h>
#include <stdlib.h>
#include "lcm/lcm_coretypes.h"

#ifndef _feedback_t_h
#define _feedback_t_h

#ifdef __cplusplus
extern "C" {
#endif

#define FEEDBACK_T_VAL 0
#define FEEDBACK_T_RATE 1
#define FEEDBACK_T_ACCEL 2

typedef struct _feedback_t feedback_t;
struct _feedback_t
{
    float      x[3];
    float      y[3];
    float      z[3];
    float      roll;
    float      pitch;
    float      yaw;
    int8_t     flags;
    int64_t    utime;
};

feedback_t   *feedback_t_copy(const feedback_t *p);
void feedback_t_destroy(feedback_t *p);

int  feedback_t_encode(void *buf, int offset, int maxlen, const feedback_t *p);
int  feedback_t_decode(const void *buf, int offset, int maxlen, feedback_t *p);
int  feedback_t_decode_cleanup(feedback_t *p);
int  feedback_t_encoded_size(const feedback_t *p);

// LCM support functions. Users should not call these
int64_t __feedback_t_get_hash(void);
int64_t __feedback_t_hash_recursive(const __lcm_hash_ptr *p);
int     __feedback_t_encode_array(void *buf, int offset, int maxlen, const feedback_t *p, int elements);
int     __feedback_t_decode_array(const void *buf, int offset, int maxlen, feedback_t *p, int elements);
int     __feedback_t_decode_array_cleanup(feedback_t *p, int elements);
int     __feedback_t_encoded_array_size(const feedback_t *p, int elements);
int     __feedback_t_clone_array(const feedback_t *p, feedback_t *q, int elements);

#ifdef __cplusplus
}
#endif

#endif
