/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "messaging/tuning_t.h"

static int __tuning_t_hash_computed;
static int64_t __tuning_t_hash;

int64_t __tuning_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __tuning_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent = p;
    cp.v = (void*)__tuning_t_get_hash;
    (void) cp;

    int64_t hash = 0xa8a3b4a4be8b8ba1LL
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __tuning_t_get_hash(void)
{
    if (!__tuning_t_hash_computed) {
        __tuning_t_hash = __tuning_t_hash_recursive(NULL);
        __tuning_t_hash_computed = 1;
    }

    return __tuning_t_hash;
}

int __tuning_t_encode_array(void *buf, int offset, int maxlen, const tuning_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KPH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KIH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].KDH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].h), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].ydot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int tuning_t_encode(void *buf, int offset, int maxlen, const tuning_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __tuning_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __tuning_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __tuning_t_encoded_array_size(const tuning_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].cmd), 1);

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].KPX), 1);

        size += __float_encoded_array_size(&(p[element].KIX), 1);

        size += __float_encoded_array_size(&(p[element].KDX), 1);

        size += __float_encoded_array_size(&(p[element].KPY), 1);

        size += __float_encoded_array_size(&(p[element].KIY), 1);

        size += __float_encoded_array_size(&(p[element].KDY), 1);

        size += __float_encoded_array_size(&(p[element].KPZ), 1);

        size += __float_encoded_array_size(&(p[element].KIZ), 1);

        size += __float_encoded_array_size(&(p[element].KDZ), 1);

        size += __float_encoded_array_size(&(p[element].KPXdot), 1);

        size += __float_encoded_array_size(&(p[element].KIXdot), 1);

        size += __float_encoded_array_size(&(p[element].KDXdot), 1);

        size += __float_encoded_array_size(&(p[element].KPYdot), 1);

        size += __float_encoded_array_size(&(p[element].KIYdot), 1);

        size += __float_encoded_array_size(&(p[element].KDYdot), 1);

        size += __float_encoded_array_size(&(p[element].KPZdot), 1);

        size += __float_encoded_array_size(&(p[element].KIZdot), 1);

        size += __float_encoded_array_size(&(p[element].KDZdot), 1);

        size += __float_encoded_array_size(&(p[element].KPH), 1);

        size += __float_encoded_array_size(&(p[element].KIH), 1);

        size += __float_encoded_array_size(&(p[element].KDH), 1);

        size += __float_encoded_array_size(&(p[element].x), 1);

        size += __float_encoded_array_size(&(p[element].y), 1);

        size += __float_encoded_array_size(&(p[element].z), 1);

        size += __float_encoded_array_size(&(p[element].h), 1);

        size += __float_encoded_array_size(&(p[element].xdot), 1);

        size += __float_encoded_array_size(&(p[element].ydot), 1);

        size += __float_encoded_array_size(&(p[element].zdot), 1);

    }
    return size;
}

int tuning_t_encoded_size(const tuning_t *p)
{
    return 8 + __tuning_t_encoded_array_size(p, 1);
}

int __tuning_t_decode_array(const void *buf, int offset, int maxlen, tuning_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDX), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDY), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDZ), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDXdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDYdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDZdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KPH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KIH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].KDH), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].h), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].xdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].ydot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].zdot), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __tuning_t_decode_array_cleanup(tuning_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].cmd), 1);

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].KPX), 1);

        __float_decode_array_cleanup(&(p[element].KIX), 1);

        __float_decode_array_cleanup(&(p[element].KDX), 1);

        __float_decode_array_cleanup(&(p[element].KPY), 1);

        __float_decode_array_cleanup(&(p[element].KIY), 1);

        __float_decode_array_cleanup(&(p[element].KDY), 1);

        __float_decode_array_cleanup(&(p[element].KPZ), 1);

        __float_decode_array_cleanup(&(p[element].KIZ), 1);

        __float_decode_array_cleanup(&(p[element].KDZ), 1);

        __float_decode_array_cleanup(&(p[element].KPXdot), 1);

        __float_decode_array_cleanup(&(p[element].KIXdot), 1);

        __float_decode_array_cleanup(&(p[element].KDXdot), 1);

        __float_decode_array_cleanup(&(p[element].KPYdot), 1);

        __float_decode_array_cleanup(&(p[element].KIYdot), 1);

        __float_decode_array_cleanup(&(p[element].KDYdot), 1);

        __float_decode_array_cleanup(&(p[element].KPZdot), 1);

        __float_decode_array_cleanup(&(p[element].KIZdot), 1);

        __float_decode_array_cleanup(&(p[element].KDZdot), 1);

        __float_decode_array_cleanup(&(p[element].KPH), 1);

        __float_decode_array_cleanup(&(p[element].KIH), 1);

        __float_decode_array_cleanup(&(p[element].KDH), 1);

        __float_decode_array_cleanup(&(p[element].x), 1);

        __float_decode_array_cleanup(&(p[element].y), 1);

        __float_decode_array_cleanup(&(p[element].z), 1);

        __float_decode_array_cleanup(&(p[element].h), 1);

        __float_decode_array_cleanup(&(p[element].xdot), 1);

        __float_decode_array_cleanup(&(p[element].ydot), 1);

        __float_decode_array_cleanup(&(p[element].zdot), 1);

    }
    return 0;
}

int tuning_t_decode(const void *buf, int offset, int maxlen, tuning_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __tuning_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __tuning_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int tuning_t_decode_cleanup(tuning_t *p)
{
    return __tuning_t_decode_array_cleanup(p, 1);
}

int __tuning_t_clone_array(const tuning_t *p, tuning_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].cmd), &(q[element].cmd), 1);

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].KPX), &(q[element].KPX), 1);

        __float_clone_array(&(p[element].KIX), &(q[element].KIX), 1);

        __float_clone_array(&(p[element].KDX), &(q[element].KDX), 1);

        __float_clone_array(&(p[element].KPY), &(q[element].KPY), 1);

        __float_clone_array(&(p[element].KIY), &(q[element].KIY), 1);

        __float_clone_array(&(p[element].KDY), &(q[element].KDY), 1);

        __float_clone_array(&(p[element].KPZ), &(q[element].KPZ), 1);

        __float_clone_array(&(p[element].KIZ), &(q[element].KIZ), 1);

        __float_clone_array(&(p[element].KDZ), &(q[element].KDZ), 1);

        __float_clone_array(&(p[element].KPXdot), &(q[element].KPXdot), 1);

        __float_clone_array(&(p[element].KIXdot), &(q[element].KIXdot), 1);

        __float_clone_array(&(p[element].KDXdot), &(q[element].KDXdot), 1);

        __float_clone_array(&(p[element].KPYdot), &(q[element].KPYdot), 1);

        __float_clone_array(&(p[element].KIYdot), &(q[element].KIYdot), 1);

        __float_clone_array(&(p[element].KDYdot), &(q[element].KDYdot), 1);

        __float_clone_array(&(p[element].KPZdot), &(q[element].KPZdot), 1);

        __float_clone_array(&(p[element].KIZdot), &(q[element].KIZdot), 1);

        __float_clone_array(&(p[element].KDZdot), &(q[element].KDZdot), 1);

        __float_clone_array(&(p[element].KPH), &(q[element].KPH), 1);

        __float_clone_array(&(p[element].KIH), &(q[element].KIH), 1);

        __float_clone_array(&(p[element].KDH), &(q[element].KDH), 1);

        __float_clone_array(&(p[element].x), &(q[element].x), 1);

        __float_clone_array(&(p[element].y), &(q[element].y), 1);

        __float_clone_array(&(p[element].z), &(q[element].z), 1);

        __float_clone_array(&(p[element].h), &(q[element].h), 1);

        __float_clone_array(&(p[element].xdot), &(q[element].xdot), 1);

        __float_clone_array(&(p[element].ydot), &(q[element].ydot), 1);

        __float_clone_array(&(p[element].zdot), &(q[element].zdot), 1);

    }
    return 0;
}

tuning_t *tuning_t_copy(const tuning_t *p)
{
    tuning_t *q = (tuning_t*) malloc(sizeof(tuning_t));
    __tuning_t_clone_array(p, q, 1);
    return q;
}

void tuning_t_destroy(tuning_t *p)
{
    __tuning_t_decode_array_cleanup(p, 1);
    free(p);
}

