/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen
 **/

#include <string.h>
#include "messaging/position_t.h"

static int __position_t_hash_computed;
static int64_t __position_t_hash;

int64_t __position_t_hash_recursive(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for (fp = p; fp != NULL; fp = fp->parent)
        if (fp->v == __position_t_get_hash)
            return 0;

    __lcm_hash_ptr cp;
    cp.parent = p;
    cp.v = (void*)__position_t_get_hash;
    (void) cp;

    int64_t hash = 0xdada4aa46479c21bLL
         + __int32_hash_recursive(&cp)
         + __int32_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
         + __float_hash_recursive(&cp)
        ;

    return (hash<<1) + ((hash>>63)&1);
}

int64_t __position_t_get_hash(void)
{
    if (!__position_t_hash_computed) {
        __position_t_hash = __position_t_hash_recursive(NULL);
        __position_t_hash_computed = 1;
    }

    return __position_t_hash;
}

int __position_t_encode_array(void *buf, int offset, int maxlen, const position_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_encode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_encode_array(buf, offset + pos, maxlen - pos, &(p[element].h), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int position_t_encode(void *buf, int offset, int maxlen, const position_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __position_t_get_hash();

    thislen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    thislen = __position_t_encode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int __position_t_encoded_array_size(const position_t *p, int elements)
{
    int size = 0, element;
    for (element = 0; element < elements; element++) {

        size += __int32_encoded_array_size(&(p[element].cmd), 1);

        size += __int32_encoded_array_size(&(p[element].timestamp), 1);

        size += __float_encoded_array_size(&(p[element].x), 1);

        size += __float_encoded_array_size(&(p[element].y), 1);

        size += __float_encoded_array_size(&(p[element].z), 1);

        size += __float_encoded_array_size(&(p[element].h), 1);

    }
    return size;
}

int position_t_encoded_size(const position_t *p)
{
    return 8 + __position_t_encoded_array_size(p, 1);
}

int __position_t_decode_array(const void *buf, int offset, int maxlen, position_t *p, int elements)
{
    int pos = 0, thislen, element;

    for (element = 0; element < elements; element++) {

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].cmd), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __int32_decode_array(buf, offset + pos, maxlen - pos, &(p[element].timestamp), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].x), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].y), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].z), 1);
        if (thislen < 0) return thislen; else pos += thislen;

        thislen = __float_decode_array(buf, offset + pos, maxlen - pos, &(p[element].h), 1);
        if (thislen < 0) return thislen; else pos += thislen;

    }
    return pos;
}

int __position_t_decode_array_cleanup(position_t *p, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_decode_array_cleanup(&(p[element].cmd), 1);

        __int32_decode_array_cleanup(&(p[element].timestamp), 1);

        __float_decode_array_cleanup(&(p[element].x), 1);

        __float_decode_array_cleanup(&(p[element].y), 1);

        __float_decode_array_cleanup(&(p[element].z), 1);

        __float_decode_array_cleanup(&(p[element].h), 1);

    }
    return 0;
}

int position_t_decode(const void *buf, int offset, int maxlen, position_t *p)
{
    int pos = 0, thislen;
    int64_t hash = __position_t_get_hash();

    int64_t this_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &this_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (this_hash != hash) return -1;

    thislen = __position_t_decode_array(buf, offset + pos, maxlen - pos, p, 1);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int position_t_decode_cleanup(position_t *p)
{
    return __position_t_decode_array_cleanup(p, 1);
}

int __position_t_clone_array(const position_t *p, position_t *q, int elements)
{
    int element;
    for (element = 0; element < elements; element++) {

        __int32_clone_array(&(p[element].cmd), &(q[element].cmd), 1);

        __int32_clone_array(&(p[element].timestamp), &(q[element].timestamp), 1);

        __float_clone_array(&(p[element].x), &(q[element].x), 1);

        __float_clone_array(&(p[element].y), &(q[element].y), 1);

        __float_clone_array(&(p[element].z), &(q[element].z), 1);

        __float_clone_array(&(p[element].h), &(q[element].h), 1);

    }
    return 0;
}

position_t *position_t_copy(const position_t *p)
{
    position_t *q = (position_t*) malloc(sizeof(position_t));
    __position_t_clone_array(p, q, 1);
    return q;
}

void position_t_destroy(position_t *p)
{
    __position_t_decode_array_cleanup(p, 1);
    free(p);
}

